---
title: "mdsR: A package suite for nursing home assessments"
author: "Kevin W. McConeghy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mdsR: 01-Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Welcome to mdsR! This program was written as a tool for academic work performed by researchers at Brown University. The primary objective was to develop a suite of personalized functions, some of which will only work with data housed by the Brown School of Public Health. We drew from many sources which are acknowledged and cited throughout in the development of this package.  

## Introduction

This vignette is a short introduction to the package for interested readers. In following vignettes describe in detail:  

1) Nursing Home Minimum Datasets [NH](https://kmcconeghy.github.io/flumodelr/articles/02-mds.html)  

2) Simple descriptive work [Check MDS](https://kmcconeghy.github.io/flumodelr/articles/03-chkmds.html)  

3) Cohort Definitions [NH Cohort](https://kmcconeghy.github.io/flumodelr/articles/04-cohort.html)  

4) Special computations / formatting [Advanced MDS](https://kmcconeghy.github.io/flumodelr/articles/05-advmds.html)  

## Contacting authors  
The primary author of the package was Kevin W. McConeghy.  
